//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities1 : DbContext
    {
        public LibraryDBEntities1()
            : base("name=LibraryDBEntities1")
        {
            this.Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<BOOK>()
                        .HasMany<AUTHOR>(b => b.AUTHORs)
                        .WithMany(a => a.BOOKs)
                        .Map(m => m.ToTable("BOOK_AUTHOR")
                        .MapLeftKey("ISBN")
                        .MapRightKey("Aid"));
        }

        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATIONs { get; set; }
    }
}
